import type { Metadata } from "next";
import { ReactNode } from "react";
import "../globals.css";
import Provider from "./Provider";
import AuthContext from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Picdiary",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <Provider>
      <AuthContext>
        <html lang="ko">
          <body>{children}</body>
        </html>
      </AuthContext>
    </Provider>
  );
}
