import type { Metadata } from "next";
import "../globals.css";

import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Picdiary",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
